version: "3.8"

services:
    mongodb:
        image: mongo
        container_name: documentdb
        ports: 
            - 27017:27017
        volumes: 
            - data:/data
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=jobs
            - MONGO_INITDB_ROOT_PASSWORD=jobs
    mongo-express:
        image: mongo-express
        container_name: jobs-express
        restart: unless-stopped
        ports:
            - 8081:8081
        depends_on: [mongodb]
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=jobs
            - ME_CONFIG_MONGODB_ADMINPASSWORD=jobs
            - ME_CONFIG_MONGODB_SERVER=mongodb
    redis:
        image: redis
        container_name: cache
        ports:
            - 6379:6379
        restart: unless-stopped
        volumes:
            - data:/data
volumes: 
    data: {} 
    
networks:
    default: 
        name: mongodb_network