version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: documentdb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jobs
      - MONGO_INITDB_ROOT_PASSWORD=jobs
    volumes:
      - data:/data
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    restart: unles-stopped
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=jobs
      - ME_CONFIG_MONGODB_ADMINPASSWORD=jobs
      - ME_CONFIG_SERVER=mongodb