spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  application:
    name: jobs-api
  data:
    mongodb:
      authentication-database: admin
      database: jobs
      username: jobs
      password: jobs
      host: localhost
      port: 27017